# Generated by Django 5.2.1 on 2025-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_alter_imagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.CharField(choices=[('imagem1', 'Imagem 1'), ('imagem2', 'Imagem 2'), ('imagem3', 'Imagem 3'), ('imagem4', 'Imagem 4'), ('imagem5', 'Imagem 5'), ('imagem6', 'Imagem 6'), ('imagem7', 'Imagem 7'), ('imagem8', 'Imagem 8'), ('imagem9', 'Imagem 9'), ('imagem10', 'Imagem 10')], max_length=50),
        ),
    ]
