# Generated by Django 5.2.1 on 2025-07-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_alter_imagem_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='acertou',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
